# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Layer.create(:name => 'UWEC Main Tour')

layer = Layer.find_by_name('UWEC Main Tour');

layer.hotspots.create([
	{	:title => 'Schofield Hall', :footnote => 'Administrative Building', 
		:latitude => '44.798606582825855', :longitude => '-91.50029999999998',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/schofield.jpg',
		:description => 'The original campus building, constructed in 1916, contains a number of offices inside: Admissions, Financial Aid and DOS.'},
	{	:title => 'Nursing Building', :footnote => 'Q\'s? Call Admissions at 836-5415!', 
		:latitude => '44.797345679328004', :longitude => '-91.50283562698365',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/nursing.jpg',
		:description => 'At the edge of a 200-acre nature area is the home of the under-graduate and graduate nursing programs, as well as the environmental public health program.	'},
	{	:title => 'L.E. Phillips Hall', :footnote => 'Q\'s? Call Admissions at 836-5415!', 
		:latitude => '44.79697818785964', :longitude => '-91.49966437301634',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/phillips.jpg',
		:description => 'Houses the natural and computer science programs, classrooms and labs, as well as greenhouses, a bird museum and the area\'s only planetarium'},
	{	:title => 'Schneider Hall', :footnote => 'Q\'s? Call Admissions at 836-5415!', 
		:latitude => '44.79794567885304', :longitude => '-91.49850000000004',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/schneider.jpg',
		:description => 'Home of the College of Business, the departments of economics, political science and sociology, Parking Office and the Honors Program.'},
	{	:title => 'Campus Mall', :footnote => 'Q\'s? Call Admissions at 836-5415!', 
		:latitude => '44.79779301075728', :longitude => '-91.50078746032716',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/campusmall.jpg',
		:description => 'This is the place where you can hang out, have a snack, play Frisbee or take a quick nap or listen to a live music performance!'},
	{	:title => 'Zorn Arena', :footnote => 'Q\'s? Call Admissions at 836-5415!', 
		:latitude => '44.79896090407378', :longitude => '-91.49853562698365',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/zorn.jpg',
		:description => 'Where we cheer on the Blugold bball teams, take in world-class entertainment through The Forum and Artists Series, attend major concerts and graduation!'},
	{	:title => 'Brewer Hall', :footnote => 'with Kjer Theater', 
		:latitude => '44.79878477394512', :longitude => '-91.49790728836058',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/kjertheater.jpg',
		:description => 'Home to many education and human sciences classes and the beloved Kjer (Care) Theatre, one of four stages on campus.'},
	{	:title => 'New Education Building', :footnote => 'Q\'s? Call Admissions at 836-5415!', 
		:latitude => '44.79851522613005', :longitude => '-91.49882186508182',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/education.jpg',
		:description => 'Will house classrooms and administrative offices along with education studies, English, foreign languages, special education and Services for Students with Disabilities.'},
	{	:title => 'Hibbard Hall', :footnote => 'Home to the Humanities', 
		:latitude => '44.799530451728266', :longitude => '-91.49790728836058',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/hibbardhumanitieshall.jpg',
		:description => 'Here you\'ll find the English, foreign languages, history, communication and journalism, psychology, mathematics, and philosophy and religious studies departments.'},
	{	:title => 'Footbridge', :footnote => 'Imagine getting this view every day!', 
		:latitude => '44.79994891515546', :longitude => '-91.50063157081604',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/footbridge.jpg',
		:description => 'The Chippewa River footbridge is one of the most iconic and scenic spots on campus. Stop midway for a panoramic view of the river, Putnam Rock, and our famous hill.'},
	{	:title => 'Haas Fine Arts', :footnote => 'Home of the Blugold Marching Band!', 
		:latitude => '44.80126592747214', :longitude => '-91.5019941329956',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/haasfineartscenter.jpg',
		:description => 'Great spaces to take in students’ work include the Foster Art Gallery, Riverside Theatre and the concert halls: Gantner and Phillips.'},
	{	:title => 'HSS', :footnote => 'Human Sciences and Services', 
		:latitude => '44.80164656127005', :longitude => '-91.50495529174805',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/humansciencesservices.jpg',
		:description => 'The location of special education, social work, and the communication sciences and disorders departments as well as the Center for Service-Learning.'},
	{	:title => 'McIntyre Library', :footnote => '3rd floor has fitness room!', 
		:latitude => '44.79820554047785', :longitude => '-91.50188684463501',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/mcintyrelibrary.jpg',
		:description => 'Five stories of incredible resources, study stations, computer labs and meeting rooms. You can check out laptops and video cameras for free.'},
	{	:title => 'Old Library', :footnote => 'Look for our model of campus!', 
		:latitude => '44.798662324962066', :longitude => '-91.50124311447144',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/oldlibrary.jpg',
		:description => 'A hallway from McIntyre Library connects with Old Library, home of our largest 24-hour computer lab, the Academic Skills Center and Counseling Services.'},
	{	:title => 'Hilltop Center', :footnote => 'Fun and Food!', 
		:latitude => '44.79787056289117', :longitude => '-91.50534152984619',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/hilltopcenter.jpg',
		:description => 'Houses University Recreation and Sport Facilities, the Bowling and Billiard Center and the Environmental Adventure Center.'},
	{	:title => 'Towers Hall', :footnote => 'Housing and Residence Life Office', 
		:latitude => '44.7970331104165', :longitude => '-91.50626420974731',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/towers.jpg',
		:description => 'All residence halls include 24- hour computer labs, FREE wireless Internet, study lounges, kitchens, laundry facilities and TV lounges.'},
	{	:title => 'McPhee Center', :footnote => 'With Ade Olson Addition', 
		:latitude => '44.79522112619191', :longitude => '-91.50344252586365',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/mcphee.jpg',
		:description => 'The kinesiology and athletic training programs are located here, along with gymnasiums, an indoor swimming pool and many other specialized facilities.'},
	{	:title => 'Crest Wellness', :footnote => 'Home of University Police', 
		:latitude => '44.79895161993177', :longitude => '-91.50741219520569',
		:image_url => 'http://www.uwec.edu/admissions/layar/uwecmaintour/images/crestwellnesscenter.jpg',
		:description => 'Includes Higherground (a food/snack area), Club Mercury Dance Club, the Fitness Center and Student Health Services.'}
])
